In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
url = "https://raw.githubusercontent.com/phinum/IME/main/total_returns.csv" 
df = pd.read_csv(url)
df = df.drop('Unnamed: 0', axis = 1)
df = df.drop('Date', axis = 1)
df

ADANIPORTS.NS  TECHM.NS  ...  POWERGRID.NS  INDUSINDBK.NS
0          0.964119  0.992982  ...      0.999645       0.969238
1          0.991277  1.010651  ...      0.987229       1.001124
2          0.984748  1.006131  ...      1.002515       1.009302
3          0.972994  0.972767  ...      0.989964       0.980454
4          0.985306  1.022220  ...      1.025706       1.023285
...             ...       ...  ...           ...            ...
999        0.990903  1.005335  ...      0.979944       0.965884
1000       0.978230  1.003474  ...      0.986788       0.987060
1001       1.027886  1.012465  ...      1.010239       1.002789
1002       0.986044  0.984083  ...      1.010395       0.978740
1003       0.977249  1.006634  ...      0.961163       1.022209

[1004 rows x 48 columns]

In [36]:
df1 = df.transpose()
df1.shape
df1.reset_index(drop=True, inplace=True)

df2 = df1.transpose()
df2_t = df2.transpose()
df2_t

0         1         2     ...      1001      1002      1003
0   0.964119  0.991277  0.984748  ...  1.027886  0.986044  0.977249
1   0.992982  1.010651  1.006131  ...  1.012465  0.984083  1.006634
2   0.995379  0.998015  1.011798  ...  1.010358  0.998911  0.996885
3   0.980632  0.991281  1.013904  ...  0.986651  0.992226  0.972496
4   0.979830  1.001752  0.989319  ...  0.993818  0.982226  0.982357
5   0.976159  0.995505  0.995624  ...  1.015039  0.988603  0.993916
6   0.951119  1.022910  0.975182  ...  1.008929  0.978255  0.978806
7   0.983079  1.004794  0.992054  ...  0.987175  1.002096  0.987210
8   1.000118  0.996276  0.998339  ...  1.012304  0.998358  0.972937
9   1.002860  0.987136  0.994221  ...  1.006600  0.992238  0.988412
10  0.998059  1.067732  0.979766  ...  1.013333  0.991928  0.978040
11  0.991696  0.992673  0.994373  ...  1.010263  1.003975  0.992961
12  0.985199  0.992566  1.017555  ...  0.993221  0.977142  0.990909
13  0.992672  0.999234  0.969986  ...  1.025569  0.989013  1.004700
14  0.994867  1.012563  1.010692  ...  0.996049  0.980378  0.972959
15  1.002248  0.998566  0.996768  ...  1.011063  0.975481  0.983797
16  1.017235  1.036757  0.977010  ...  1.023506  0.983541  0.975676
17  0.973094  1.034597  1.001213  ...  1.000793  0.977030  0.976490
18  0.988989  0.998086  0.991024  ...  1.007474  0.998904  0.996504
19  0.973495  0.994144  1.000823  ...  0.991137  0.982006  0.984418
20  0.980061  0.998695  1.010084  ...  1.029196  0.978193  0.989608
21  1.002333  1.022536  0.984178  ...  1.010033  1.004480  0.994820
22  1.007167  0.980829  1.021282  ...  0.957580  1.007335  0.997493
23  0.984314  1.037979  1.018534  ...  1.003393  0.990279  0.968417
24  0.970673  1.000505  0.998171  ...  0.991841  0.986227  0.984392
25  0.986239  1.007651  0.993266  ...  1.010111  1.017352  1.010984
26  0.966824  0.994000  0.999917  ...  0.988752  1.004471  0.999586
27  0.981942  1.005392  0.981548  ...  1.009170  0.982865  0.998767
28  0.985237  1.003343  1.018494  ...  1.009684  1.003689  0.967656
29  0.971520  1.005877  1.029485  ...  1.002739  0.999111  0.979630
30  0.987528  0.997009  0.981136  ...  1.001894  1.001448  0.984766
31  0.998154  0.989471  1.000431  ...  0.992636  0.994141  1.007208
32  0.987751  0.993110  0.996172  ...  1.027302  0.974268  0.979434
33  0.969818  1.003474  0.994136  ...  1.008856  0.992563  1.038999
34  0.988475  0.986675  1.006446  ...  1.010045  0.983774  0.966746
35  0.959765  0.989749  0.996135  ...  0.997964  0.999082  1.013577
36  0.982037  0.992058  0.985230  ...  1.007088  0.998371  1.007876
37  0.974208  1.000756  0.984049  ...  1.014146  1.003295  0.999343
38  0.981647  1.015961  0.982224  ...  1.009005  0.982575  0.942474
39  0.968832  0.986633  0.995867  ...  1.004284  0.981830  1.024944
40  0.980253  1.009897  1.026911  ...  1.005504  0.975606  0.977766
41  0.992880  0.990979  1.018240  ...  1.048896  0.987622  1.000367
42  0.974439  0.995552  0.986826  ...  0.997422  0.994084  0.997811
43  0.983238  0.992433  1.004424  ...  1.010342  0.992070  1.000204
44  0.938169  0.993104  0.977166  ...  1.067859  0.990162  0.948443
45  0.971672  1.004502  0.974289  ...  0.996971  1.010634  0.987693
46  0.999645  0.987229  1.002515  ...  1.010239  1.010395  0.961163
47  0.969238  1.001124  1.009302  ...  1.002789  0.978740  1.022209

[48 rows x 1004 columns]

In [38]:
cov = np.cov(df2_t)
cov

array([[4.58991123e-04, 5.58997405e-05, 7.94148937e-05, ...,
        1.48820567e-04, 4.99662365e-05, 1.12802653e-04],
       [5.58997405e-05, 2.95439696e-04, 4.35049074e-05, ...,
        4.18873342e-05, 1.16696376e-05, 3.58545801e-05],
       [7.94148937e-05, 4.35049074e-05, 2.18138685e-04, ...,
        6.33394986e-05, 1.98534914e-05, 8.22886368e-05],
       ...,
       [1.48820567e-04, 4.18873342e-05, 6.33394986e-05, ...,
        3.82322546e-04, 5.77949662e-05, 9.81136277e-05],
       [4.99662365e-05, 1.16696376e-05, 1.98534914e-05, ...,
        5.77949662e-05, 1.76804846e-04, 3.73201112e-05],
       [1.12802653e-04, 3.58545801e-05, 8.22886368e-05, ...,
        9.81136277e-05, 3.73201112e-05, 3.21014781e-04]])

In [39]:
np.shape(cov)

(48, 48)

In [40]:
mean = df2.mean().values

In [41]:
mean

array([1.00055117, 1.00057221, 1.00086809, 1.00064569, 0.99956586,
       1.00046027, 1.00106165, 1.000149  , 1.00044392, 1.0009379 ,
       1.00082007, 1.00003558, 0.99973597, 1.00018132, 1.00066555,
       1.00021136, 1.00108644, 1.00031453, 1.00076458, 1.00057606,
       1.00107187, 1.00081279, 1.00035375, 1.00025559, 1.00045094,
       1.00033008, 1.00075275, 1.00002159, 1.00077815, 1.00085616,
       1.00053038, 1.00141051, 1.00173736, 1.00093593, 0.99952815,
       1.00066191, 1.00006218, 1.00058422, 0.99976127, 1.00057346,
       1.00114357, 1.0021995 , 1.00064628, 1.00086268, 0.99955973,
       1.00097332, 1.0003687 , 1.00042618])

In [42]:
import numpy as np
from sklearn.covariance import EmpiricalCovariance
from sklearn.datasets import make_gaussian_quantiles
real_cov = np.cov(df2_t)
rng = np.random.RandomState(0)
X = rng.multivariate_normal(mean = mean, cov= real_cov, size= 500)
cov = EmpiricalCovariance().fit(X)


In [43]:
real_cov

array([[4.58991123e-04, 5.58997405e-05, 7.94148937e-05, ...,
        1.48820567e-04, 4.99662365e-05, 1.12802653e-04],
       [5.58997405e-05, 2.95439696e-04, 4.35049074e-05, ...,
        4.18873342e-05, 1.16696376e-05, 3.58545801e-05],
       [7.94148937e-05, 4.35049074e-05, 2.18138685e-04, ...,
        6.33394986e-05, 1.98534914e-05, 8.22886368e-05],
       ...,
       [1.48820567e-04, 4.18873342e-05, 6.33394986e-05, ...,
        3.82322546e-04, 5.77949662e-05, 9.81136277e-05],
       [4.99662365e-05, 1.16696376e-05, 1.98534914e-05, ...,
        5.77949662e-05, 1.76804846e-04, 3.73201112e-05],
       [1.12802653e-04, 3.58545801e-05, 8.22886368e-05, ...,
        9.81136277e-05, 3.73201112e-05, 3.21014781e-04]])

In [44]:
cov.covariance_

array([[4.23099237e-04, 4.39252580e-05, 6.46404374e-05, ...,
        1.57578183e-04, 4.80649039e-05, 9.97012832e-05],
       [4.39252580e-05, 2.80682048e-04, 2.09861871e-05, ...,
        5.76606174e-05, 8.47544835e-07, 4.27417321e-06],
       [6.46404374e-05, 2.09861871e-05, 2.02851310e-04, ...,
        7.80779802e-05, 1.44054638e-05, 8.50900202e-05],
       ...,
       [1.57578183e-04, 5.76606174e-05, 7.80779802e-05, ...,
        4.52470620e-04, 7.08224027e-05, 1.20055280e-04],
       [4.80649039e-05, 8.47544835e-07, 1.44054638e-05, ...,
        7.08224027e-05, 2.01443203e-04, 4.62932186e-05],
       [9.97012832e-05, 4.27417321e-06, 8.50900202e-05, ...,
        1.20055280e-04, 4.62932186e-05, 2.82798377e-04]])